<a href="https://colab.research.google.com/github/dani3l-ruiizp/Entregables_2/blob/master/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## Numpy

import numpy as np

# 1. crear un arreglo

# 1.1 desde listas
arr = np.array([5, 10, 15, 20])
print("Arreglo desde listas: ")
print(arr)
print("\n")

# 1.2 desde matrices
mat = np.array([[2, 4, 6], [8, 10, 12]])
print("Matriz: ")
print(mat)
print("\n")

# 1.3 con rangos
range = np.arange(5, 25, 5)
print("Arreglo con rangos: ")
print(range)
print("\n")

# 1.4 arreglo con ceros y unos
zeros = np.zeros((2,4))
ones = np.ones((3,3))
print("Arreglo de ceros: ")
print(zeros)
print("\n")
print("Arreglo de unos: ")
print(ones)
print("\n")

# 1.5 aleatorios
random = np.random.rand(4,4)
random_int = np.random.randint(10,200,(3,3))

print("Arreglo aleatorio: ")
print(random)
print("\n")
print("Arreglo aleatorio de enteros: ")
print(random_int)
# arreglo
arr2 = np.array([100, 200, 300, 400, 500])
index = arr2[2]
index_range = arr2[1:4]
slicing = arr2[::-1]

print("indice: ")
print(index)
print("indice con rango: ")
print(index_range)
print("slicing: ")
print(slicing)
print("\n")

# Matrices
mat2 = np.array([[10,20,30],[40,50,60],[70,80,90]])
index2 = mat2[2,1]
index_column = mat2[:,2]
index_row = mat2[0,:]
submatriz = mat2[1:3,0:2]

print("matriz: ")
print(mat2)
print("indice: ")
print(index2)
print("indice columna: ")
print(index_column)
print("indice fila: ")
print(index_row)
psum = arr + 3
print("suma: ")
print(sum)

mult = arr * 3
print("multiplicacion: ")
print(mult)

div = arr / 4
print("division: ")
print(div)

exp = arr ** 3
print("exponente: ")
print(exp)

# entre arreglos
a = np.array([2,4,6])
b = np.array([1,3,5])

sum_arr = a + b
mult_arr = a * b
div_arr = a / b
exp_arr = a ** b

print("suma de arreglos: ")
print(sum_arr)
print("multiplicacion de arreglos: ")
print(mult_arr)
print("division de arreglos: ")
print(div_arr)
print("exponente de arreglos: ")
print(exp_arr)
print("submatriz: ")
print(submatriz)
sqrt = np.sqrt(arr)
print("Raiz cuadrada: ")
print(sqrt)

mean = np.mean(arr)
print("Media: ")
print(mean)

sumx = np.sum(arr)
print("Suma: ")
print(sumx)

max = np.max(arr)
print("Maximo: ")
print(max)

min = np.min(arr)
print("Minimo: ")
print(min)

std = np.std(arr)
print("desviacion estandar: ")
print(std)


Arreglo desde listas: 
[ 5 10 15 20]


Matriz: 
[[ 2  4  6]
 [ 8 10 12]]


Arreglo con rangos: 
[ 5 10 15 20]


Arreglo de ceros: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Arreglo de unos: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Arreglo aleatorio: 
[[0.16488747 0.48359233 0.22032541 0.6853824 ]
 [0.83364428 0.15157168 0.66177677 0.3967171 ]
 [0.68315955 0.7247375  0.54864594 0.42445677]
 [0.60625937 0.74029943 0.21497856 0.48552872]]


Arreglo aleatorio de enteros: 
[[ 15 198 120]
 [ 97 117  11]
 [ 51 130  17]]
indice: 
300
indice con rango: 
[200 300 400]
slicing: 
[500 400 300 200 100]


matriz: 
[[10 20 30]
 [40 50 60]
 [70 80 90]]
indice: 
80
indice columna: 
[30 60 90]
indice fila: 
[10 20 30]
suma: 
<built-in function sum>
multiplicacion: 
[15 30 45 60]
division: 
[1.25 2.5  3.75 5.  ]
exponente: 
[ 125 1000 3375 8000]
suma de arreglos: 
[ 3  7 11]
multiplicacion de arreglos: 
[ 2 12 30]
division de arreglos: 
[2.         1.33333333 1.2       ]
exponente de arreglos: 
[   2   64 7776]
su